name: table_calendar
description: Highly customizable, feature-packed calendar widget for Flutter.
version: 3.1.2
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
